// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zMoney: z.AnyZodObject = z.object({
    amount: z.number().int().optional(),
    currency: z.string().optional(),
    conversion: z.union([
        z.lazy(() => {
            return zConversion;
        }),
        z.null()
    ]).optional()
});

export const zConversion: z.AnyZodObject = z.object({
    rounding: z.string().optional(),
    from: zMoney.optional(),
    to: zMoney.optional(),
    rate: z.number().optional(),
    date: z.string().optional(),
    provider: z.string().optional()
});

export const zMoneyOutput: z.AnyZodObject = z.object({
    amount: z.number().int().gt(0),
    currency: z.string(),
    conversion: z.union([
        zConversion,
        z.null()
    ]).optional()
});

/**
 * v4 features an advanced economy model under the hood.
 * Accountings are implemented as a common interface for issuing and receiving Transactions,
 * which allows different resources to have money-capabalities.
 * \
 * \
 * Many different actions can trigger changes in Accountings, such as GatewayCheckouts being successfully charged.
 */
export const zAccounting: z.AnyZodObject = z.object({
    id: z.number().int().optional(),
    owner: z.string().optional(),
    ownerObject: z.string().optional(),
    currency: z.string().optional(),
    balance: zMoneyOutput.optional()
});

export const zMoneyJsonld: z.AnyZodObject = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.number().int().optional(),
    currency: z.string().optional(),
    conversion: z.union([
        z.lazy(() => {
            return zConversionJsonld;
        }),
        z.null()
    ]).optional()
});

export const zConversionJsonld: z.AnyZodObject = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    rounding: z.string().optional(),
    from: zMoneyJsonld.optional(),
    to: zMoneyJsonld.optional(),
    rate: z.number().optional(),
    date: z.string().optional(),
    provider: z.string().optional()
});

export const zMoneyOutputJsonld: z.AnyZodObject = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.number().int().gt(0),
    currency: z.string(),
    conversion: z.union([
        zConversionJsonld,
        z.null()
    ]).optional()
});

/**
 * v4 features an advanced economy model under the hood.
 * Accountings are implemented as a common interface for issuing and receiving Transactions,
 * which allows different resources to have money-capabalities.
 * \
 * \
 * Many different actions can trigger changes in Accountings, such as GatewayCheckouts being successfully charged.
 */
export const zAccountingJsonld: z.AnyZodObject = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().optional(),
    owner: z.string().optional(),
    ownerObject: z.string().optional(),
    currency: z.string().optional(),
    balance: zMoneyOutputJsonld.optional()
});

/**
 * AccountingBalancePoints represent a dated aggregate Accounting balance.\
 * \
 * Each point is the sum of money at incoming and outgoing transactions in an Accounting for a period of time,
 * you can query multiple balance points to obtain the evolution of the Accounting's balance over time.
 */
export const zAccountingBalancePoint = z.object({
    start: z.string().datetime().optional(),
    end: z.string().datetime().optional(),
    balance: zMoneyOutput.optional(),
    length: z.number().int().optional()
});

/**
 * AccountingBalancePoints represent a dated aggregate Accounting balance.\
 * \
 * Each point is the sum of money at incoming and outgoing transactions in an Accounting for a period of time,
 * you can query multiple balance points to obtain the evolution of the Accounting's balance over time.
 */
export const zAccountingBalancePointJsonld = z.object({
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    start: z.string().datetime().optional(),
    end: z.string().datetime().optional(),
    balance: zMoneyOutputJsonld.optional(),
    length: z.number().int().optional()
});

/**
 * AccountingTransactions represent a movement of money from one Accounting (origin) into another (target).\
 * \
 * When a transaction targets an Accounting it means that the Accounting receives it, this will add to that Accounting.
 * When a transaction originates from an Accounting the Accounting issues the transaction and it will deduct from it if,
 * specially when the transaction comes from a GatewayCharge processed by the `wallet` Gateway.\
 * \
 * AccountingTransactions are generated for each GatewayCharge in a GatewayCheckout once it becomes successful.
 */
export const zAccountingTransaction = z.object({
    id: z.number().int().readonly().optional(),
    money: zMoneyOutput.optional(),
    origin: z.string().optional(),
    target: z.string().optional()
});

/**
 * AccountingTransactions represent a movement of money from one Accounting (origin) into another (target).\
 * \
 * When a transaction targets an Accounting it means that the Accounting receives it, this will add to that Accounting.
 * When a transaction originates from an Accounting the Accounting issues the transaction and it will deduct from it if,
 * specially when the transaction comes from a GatewayCharge processed by the `wallet` Gateway.\
 * \
 * AccountingTransactions are generated for each GatewayCharge in a GatewayCheckout once it becomes successful.
 */
export const zAccountingTransactionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    money: zMoneyOutputJsonld.optional(),
    origin: z.string().optional(),
    target: z.string().optional()
});

export const zBudgetSummary = z.object({
    money: zMoneyOutput.optional(),
    task: zMoneyOutput.optional(),
    material: zMoneyOutput.optional(),
    infra: zMoneyOutput.optional()
});

export const zBudget = z.object({
    minimum: zBudgetSummary.optional(),
    optimum: zBudgetSummary.optional()
});

export const zBudgetSummaryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    money: zMoneyOutputJsonld.optional(),
    task: zMoneyOutputJsonld.optional(),
    material: zMoneyOutputJsonld.optional(),
    infra: zMoneyOutputJsonld.optional()
});

export const zBudgetJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    minimum: zBudgetSummaryJsonld.optional(),
    optimum: zBudgetSummaryJsonld.optional()
});

export const zCategory = z.object({
    id: z.string().optional()
});

export const zCategoryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.string().optional()
});

export const zMoneyInput = z.object({
    amount: z.number().int().gt(0),
    currency: z.string()
});

export const zChargeCreationDto = z.object({
    type: z.enum([
        'single',
        'recurring'
    ]),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    target: z.string(),
    money: zMoneyInput
});

export const zMoneyInputJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.number().int().gt(0),
    currency: z.string()
});

export const zChargeCreationDtoJsonld = z.object({
    type: z.enum([
        'single',
        'recurring'
    ]),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    target: z.string(),
    money: zMoneyInputJsonld
});

/**
 * Unprocessable entity
 */
export const zConstraintViolationJson = z.object({
    status: z.number().int().optional().default(422),
    violations: z.array(z.object({
        propertyPath: z.string().optional(),
        message: z.string().optional()
    })).optional(),
    detail: z.string().readonly().optional(),
    type: z.string().readonly().optional(),
    title: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    instance: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional()
});

/**
 * Unprocessable entity
 */
export const zConstraintViolationJsonldJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    status: z.number().int().optional().default(422),
    violations: z.array(z.object({
        propertyPath: z.string().optional(),
        message: z.string().optional()
    })).optional(),
    detail: z.string().readonly().optional(),
    description: z.string().readonly().optional(),
    type: z.string().readonly().optional(),
    title: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    instance: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional()
});

/**
 * A representation of common errors.
 */
export const zError = z.object({
    title: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    detail: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    status: z.number().optional().default(400),
    instance: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    type: z.string().readonly().optional()
});

/**
 * A representation of common errors.
 */
export const zErrorJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    title: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    detail: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    status: z.number().optional().default(400),
    instance: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    type: z.string().readonly().optional(),
    description: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional()
});

/**
 * Gateways represent payment services used to perform the necessary payments for Transactions between Accounts.\
 * \
 * For each Gateway there is an internal implementation that handles the creation and validation of Transactions between Accounts.
 * These implementations make use of external or internal services to gather the funds that are inside a Transaction,
 * perform corroboration of funds and store the Transactions into the system.
 */
export const zGateway = z.object({
    name: z.string().optional(),
    supports: z.array(z.enum([
        'single',
        'recurring'
    ])).optional()
});

/**
 * Gateways represent payment services used to perform the necessary payments for Transactions between Accounts.\
 * \
 * For each Gateway there is an internal implementation that handles the creation and validation of Transactions between Accounts.
 * These implementations make use of external or internal services to gather the funds that are inside a Transaction,
 * perform corroboration of funds and store the Transactions into the system.
 */
export const zGatewayJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    name: z.string().optional(),
    supports: z.array(z.enum([
        'single',
        'recurring'
    ])).optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayCharge = z.object({
    id: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    checkout: z.string().optional(),
    type: z.enum([
        'single',
        'recurring'
    ]),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    target: z.string(),
    money: zMoneyOutput,
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeChargeUpdationDto = z.object({
    id: z.number().int().readonly().optional(),
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).optional()
});

/**
 * A Charge represents a payment item to be included in a Checkout for payment at a Gateway.
 */
export const zGatewayChargeJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    checkout: z.string().optional(),
    type: z.enum([
        'single',
        'recurring'
    ]),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    target: z.string(),
    money: zMoneyOutputJsonld,
    status: z.enum([
        'to_charge',
        'in_charge',
        'to_refund',
        'refunded',
        'to_wallet',
        'walleted'
    ]).optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

export const zGatewayLink = z.object({
    method: z.string().optional(),
    type: z.enum([
        'debug',
        'payment'
    ]).optional(),
    url: z.string().optional(),
    rel: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zTracking = z.object({
    title: z.string().optional(),
    value: z.string().optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckout = z.object({
    id: z.number().int().readonly().optional(),
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zGatewayCharge).min(1),
    returnUrl: z.string().url(),
    refund: z.enum([
        'to_wallet',
        'to_gateway'
    ]).optional(),
    status: z.enum([
        'to_charge',
        'charged'
    ]).optional(),
    links: z.array(zGatewayLink).readonly().optional(),
    trackings: z.array(zTracking).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutCreationDto = z.object({
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zChargeCreationDto).min(1),
    returnUrl: z.string().url(),
    refund: z.enum([
        'to_wallet',
        'to_gateway'
    ]).optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutCreationDtoJsonld = z.object({
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zChargeCreationDtoJsonld).min(1),
    returnUrl: z.string().url(),
    refund: z.enum([
        'to_wallet',
        'to_gateway'
    ]).optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutCheckoutUpdationDto = z.object({
    id: z.number().int().readonly().optional(),
    refund: z.enum([
        'to_wallet',
        'to_gateway'
    ]).optional()
});

export const zGatewayLinkJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    method: z.string().optional(),
    type: z.enum([
        'debug',
        'payment'
    ]).optional(),
    url: z.string().optional(),
    rel: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zTrackingJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    title: z.string().optional(),
    value: z.string().optional()
});

/**
 * A GatewayCheckout represents a payment session with a Gateway.
 */
export const zGatewayCheckoutJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    gateway: z.string(),
    origin: z.string(),
    charges: z.array(zGatewayChargeJsonld).min(1),
    returnUrl: z.string().url(),
    refund: z.enum([
        'to_wallet',
        'to_gateway'
    ]).optional(),
    status: z.enum([
        'to_charge',
        'charged'
    ]).optional(),
    links: z.array(zGatewayLinkJsonld).readonly().optional(),
    trackings: z.array(zTrackingJsonld).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

export const zLink = z.object({
    url: z.string().optional(),
    rel: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zLinkJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    url: z.string().optional(),
    rel: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zTerritory = z.object({
    country: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subLvl1: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subLvl2: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * A MatchCall is a managed event which accepts MatchCallSubmissions from Projects to receive *matchfunding* financement.
 * This means money going to a Project in a MatchCall can be matched with funds from the MatchCall accounting.
 * \
 * \
 * MatchCallSubmissions from Projects can be accepted or rejected by the managers.
 * \
 * \
 * How and when does a MatchCall match funds is determined by the MatchStrategy.
 * Everytime there is a Charge item going to a Project accepted in a MatchCall the strategy is evaluated for matching.
 * The strategy defines a series of rules that determine if the Charge is eligible for triggering the matching of funds.
 * When a Charge is to be matched the strategy uses a MatchFormula,
 * which is a predefined implementation for common mathematical operations used to match money.
 * The formula is fine-tuned in the strategy by defining the variables in the formula.
 */
export const zMatchCall = z.object({
    id: z.number().int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    strategies: z.array(z.string()).readonly().optional(),
    submissions: z.array(z.string()).readonly().optional(),
    managers: z.array(z.string()).optional(),
    title: z.string(),
    description: z.string().optional(),
    territory: zTerritory,
    status: z.enum([
        'in_editing',
        'in_calling',
        'in_matchmaking',
        'to_closed',
        'closed'
    ]).optional()
});

export const zTerritoryJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    country: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subLvl1: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subLvl2: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * A MatchCall is a managed event which accepts MatchCallSubmissions from Projects to receive *matchfunding* financement.
 * This means money going to a Project in a MatchCall can be matched with funds from the MatchCall accounting.
 * \
 * \
 * MatchCallSubmissions from Projects can be accepted or rejected by the managers.
 * \
 * \
 * How and when does a MatchCall match funds is determined by the MatchStrategy.
 * Everytime there is a Charge item going to a Project accepted in a MatchCall the strategy is evaluated for matching.
 * The strategy defines a series of rules that determine if the Charge is eligible for triggering the matching of funds.
 * When a Charge is to be matched the strategy uses a MatchFormula,
 * which is a predefined implementation for common mathematical operations used to match money.
 * The formula is fine-tuned in the strategy by defining the variables in the formula.
 */
export const zMatchCallJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    strategies: z.array(z.string()).readonly().optional(),
    submissions: z.array(z.string()).readonly().optional(),
    managers: z.array(z.string()).optional(),
    title: z.string(),
    description: z.string().optional(),
    territory: zTerritoryJsonld,
    status: z.enum([
        'in_editing',
        'in_calling',
        'in_matchmaking',
        'to_closed',
        'closed'
    ]).optional()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmission = z.object({
    id: z.number().int().readonly().optional(),
    call: z.string().readonly().optional(),
    project: z.string().readonly().optional(),
    status: z.enum([
        'to_review',
        'in_review',
        'accepted',
        'rejected'
    ]).optional()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionMatchCallSubmissionCreationDto = z.object({
    call: z.string(),
    project: z.string()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionMatchCallSubmissionCreationDtoJsonld = z.object({
    call: z.string(),
    project: z.string()
});

/**
 * MatchCallSubmissions represent the will of a Project to be held under a MatchCall and receive matchfunding financement.
 */
export const zMatchCallSubmissionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    call: z.string().readonly().optional(),
    project: z.string().readonly().optional(),
    status: z.enum([
        'to_review',
        'in_review',
        'accepted',
        'rejected'
    ]).optional()
});

/**
 * A MatchFormula is a predefined code implementation for matching funds in Transactions under a MatchCall.
 * MatchFormulas can be chosen by the managers in a MatchCall and their behaviour fine-tuned.
 */
export const zMatchFormula = z.object({
    name: z.string().readonly().optional(),
    expression: z.string().readonly().optional()
});

/**
 * A MatchFormula is a predefined code implementation for matching funds in Transactions under a MatchCall.
 * MatchFormulas can be chosen by the managers in a MatchCall and their behaviour fine-tuned.
 */
export const zMatchFormulaJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    name: z.string().readonly().optional(),
    expression: z.string().readonly().optional()
});

/**
 * A MatchRule is a predefined code implementation for validating
 * that a match making condition is met when there is a Charge to be matched.
 */
export const zMatchRule = z.object({
    name: z.string().readonly().optional(),
    description: z.string().readonly().optional()
});

/**
 * A MatchRule is a predefined code implementation for validating
 * that a match making condition is met when there is a Charge to be matched.
 */
export const zMatchRuleJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    name: z.string().readonly().optional(),
    description: z.string().readonly().optional()
});

/**
 * A MatchStrategy defines how will a MatchCall perform the match-making process.
 * \
 * The match-making flow is:
 * 1. A Project accepted in a MatchCall receives a successful Charge.
 * 2. The match-making loads the MatchCall's MatchStrategies.
 * 3. For each MatchStrategy the rules are executed, if one rule fails the match-making is cancelled for the strategy.
 * 3. The first valid MatchStrategy's formula function is passed the respective limit, factor and money of the MatchAgainst.
 * 4. The result of the MatchStrategy formula function execution is put in a Transaction from the MatchCall to the Project.
 */
export const zMatchStrategy = z.object({
    id: z.number().int().readonly().optional(),
    call: z.string(),
    ranking: z.number().int().gte(0).optional().default(0),
    rules: z.array(z.string()).optional(),
    formula: z.string(),
    limit: zMoneyInput,
    factor: z.number().gt(0),
    against: z.enum([
        'charge',
        'budget_min',
        'budget_opt'
    ]).optional()
});

/**
 * A MatchStrategy defines how will a MatchCall perform the match-making process.
 * \
 * The match-making flow is:
 * 1. A Project accepted in a MatchCall receives a successful Charge.
 * 2. The match-making loads the MatchCall's MatchStrategies.
 * 3. For each MatchStrategy the rules are executed, if one rule fails the match-making is cancelled for the strategy.
 * 3. The first valid MatchStrategy's formula function is passed the respective limit, factor and money of the MatchAgainst.
 * 4. The result of the MatchStrategy formula function execution is put in a Transaction from the MatchCall to the Project.
 */
export const zMatchStrategyJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    call: z.string(),
    ranking: z.number().int().gte(0).optional().default(0),
    rules: z.array(z.string()).optional(),
    formula: z.string(),
    limit: zMoneyInputJsonld,
    factor: z.number().gt(0),
    against: z.enum([
        'charge',
        'budget_min',
        'budget_opt'
    ]).optional()
});

/**
 * Sometimes an Organization is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an individual, to exist all at the same level.\
 * \
 * All Organization records are only visible to their respective owners and platform admins.
 * Sensitive data is encrypted before being stored in the database.
 */
export const zOrganization = z.object({
    user: z.string().readonly().optional(),
    taxId: z.string(),
    legalName: z.string(),
    businessName: z.string().optional()
});

/**
 * Sometimes an Organization is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an individual, to exist all at the same level.\
 * \
 * All Organization records are only visible to their respective owners and platform admins.
 * Sensitive data is encrypted before being stored in the database.
 */
export const zOrganizationJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    user: z.string().readonly().optional(),
    taxId: z.string(),
    legalName: z.string(),
    businessName: z.string().optional()
});

/**
 * Most times a real person is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an organization, to exist all at the same level.\
 * \
 * All Person records are only visible to their respective owners and platform admins.
 * Sensitive personal data is encrypted before being stored in the database.
 */
export const zPerson = z.object({
    user: z.string().readonly().optional(),
    taxId: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

/**
 * Most times a real person is behind a User account,
 * we keep their data separated from the User record to allow for other User types,
 * like the ones owned by an organization, to exist all at the same level.\
 * \
 * All Person records are only visible to their respective owners and platform admins.
 * Sensitive personal data is encrypted before being stored in the database.
 */
export const zPersonJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    user: z.string().readonly().optional(),
    taxId: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

export const zPing = z.object({
    time: z.number().int().optional(),
    message: z.string().optional()
});

export const zPingJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    time: z.number().int().optional(),
    message: z.string().optional()
});

export const zProjectCalendar = z.object({
    release: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    minimum: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    optimum: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zProjectVideo = z.object({
    src: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cover: z.union([
        z.string(),
        z.null()
    ]).optional(),
    thumbnail: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProject = z.object({
    id: z.number().int().readonly().optional(),
    slug: z.string().readonly().optional(),
    accounting: z.string().readonly().optional(),
    owner: z.string().readonly().optional(),
    title: z.string(),
    subtitle: z.string(),
    deadline: z.enum([
        'minimum',
        'optimum'
    ]).optional(),
    calendar: zProjectCalendar.optional(),
    categories: z.array(z.string()),
    territory: zTerritory,
    description: z.string(),
    video: zProjectVideo.optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.request_change',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.request_change',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional(),
    rewards: z.array(z.string()).readonly().optional(),
    budget: zBudget.optional(),
    budgetItems: z.array(z.string()).readonly().optional(),
    updates: z.array(z.string()).readonly().optional(),
    matchCallSubmissions: z.array(z.string()).readonly().optional(),
    links: z.array(zLink).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectCreationDto = z.object({
    title: z.string().regex(/^(.*[a-zA-Z]{1,}.*)$/),
    subtitle: z.string(),
    categories: z.array(zCategory).min(1).max(2),
    release: z.string().datetime().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.request_change',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.request_change',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectCreationDtoJsonld = z.object({
    title: z.string().regex(/^(.*[a-zA-Z]{1,}.*)$/),
    subtitle: z.string(),
    categories: z.array(zCategoryJsonld).min(1).max(2),
    release: z.string().datetime().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.request_change',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.request_change',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectProjectUpdationDto = z.object({
    id: z.number().int().readonly().optional(),
    title: z.string().regex(/^(.*[a-zA-Z]{1,}.*)$/).optional(),
    subtitle: z.string().optional(),
    categories: z.array(zCategory).min(1).max(2).optional(),
    territory: zTerritory.optional(),
    description: z.string().optional(),
    deadline: z.enum([
        'minimum',
        'optimum'
    ]).optional(),
    video: z.string().url().optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.request_change',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.request_change',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional()
});

export const zProjectCalendarJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    release: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    minimum: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    optimum: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zProjectVideoJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    src: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cover: z.union([
        z.string(),
        z.null()
    ]).optional(),
    thumbnail: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Projects describe a User-owned, community-led event that is to be discovered, developed and funded by the community.
 */
export const zProjectJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    slug: z.string().readonly().optional(),
    accounting: z.string().readonly().optional(),
    owner: z.string().readonly().optional(),
    title: z.string(),
    subtitle: z.string(),
    deadline: z.enum([
        'minimum',
        'optimum'
    ]).optional(),
    calendar: zProjectCalendarJsonld.optional(),
    categories: z.array(z.string()),
    territory: zTerritoryJsonld,
    description: z.string(),
    video: zProjectVideoJsonld.optional(),
    status: z.enum([
        'in_draft',
        'to_campaign_review',
        'in_campaign_review',
        'in_campaign_review.request_change',
        'campaign_review.rejected',
        'to_campaign',
        'in_campaign',
        'campaign.failed',
        'to_funding_review',
        'in_funding_review',
        'in_funding_review.request_change',
        'funding_review.rejected',
        'to_funding',
        'in_funding',
        'funding.paid'
    ]).optional(),
    rewards: z.array(z.string()).readonly().optional(),
    budget: zBudgetJsonld.optional(),
    budgetItems: z.array(z.string()).readonly().optional(),
    updates: z.array(z.string()).readonly().optional(),
    matchCallSubmissions: z.array(z.string()).readonly().optional(),
    links: z.array(zLinkJsonld).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A Project's budget is composed via BudgetItem records.\
 * \
 * Each BudgetItem describes one specific monetary necessity. The total budget of a Project is then calculated from the related BudgetItems.
 */
export const zProjectBudgetItem = z.object({
    id: z.number().int().readonly().optional(),
    project: z.string().optional(),
    type: z.enum([
        'infrastructure',
        'material',
        'task'
    ]),
    title: z.string(),
    description: z.string(),
    money: zMoneyInput,
    deadline: z.enum([
        'minimum',
        'optimum'
    ]),
    locales: z.array(z.string()).readonly().optional()
});

/**
 * A Project's budget is composed via BudgetItem records.\
 * \
 * Each BudgetItem describes one specific monetary necessity. The total budget of a Project is then calculated from the related BudgetItems.
 */
export const zProjectBudgetItemJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    project: z.string().optional(),
    type: z.enum([
        'infrastructure',
        'material',
        'task'
    ]),
    title: z.string(),
    description: z.string(),
    money: zMoneyInputJsonld,
    deadline: z.enum([
        'minimum',
        'optimum'
    ]),
    locales: z.array(z.string()).readonly().optional()
});

/**
 * ProjectCollaborations are used as requests for help on specific problems that the Project might face and cannot be budgeted-in.
 */
export const zProjectCollaboration = z.object({
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string(),
    isFulfilled: z.boolean().default(false),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * ProjectCollaborations are used as requests for help on specific problems that the Project might face and cannot be budgeted-in.
 */
export const zProjectCollaborationJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.string(),
    isFulfilled: z.boolean().default(false),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A ProjectReward is something the Project owner wishes to give in exchange for contributions to their Project.
 */
export const zProjectReward = z.object({
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]),
    money: zMoneyInput,
    isFinite: z.boolean().default(false),
    unitsTotal: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unitsClaimed: z.number().int().readonly().optional().default(0),
    unitsAvailable: z.number().int().readonly().optional().default(0),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A ProjectReward is something the Project owner wishes to give in exchange for contributions to their Project.
 */
export const zProjectRewardJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]),
    money: zMoneyInputJsonld,
    isFinite: z.boolean().default(false),
    unitsTotal: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unitsClaimed: z.number().int().readonly().optional().default(0),
    unitsAvailable: z.number().int().readonly().optional().default(0),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaim = z.object({
    id: z.number().int().readonly().optional(),
    owner: z.string().readonly().optional(),
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimRewardClaimCreationDto = z.object({
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimRewardClaimCreationDtoJsonld = z.object({
    charge: z.string(),
    reward: z.string()
});

/**
 * A ProjectRewardClaim represents the will of an User who wishes to obtain one ProjectReward.
 */
export const zProjectRewardClaimJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    owner: z.string().readonly().optional(),
    charge: z.string(),
    reward: z.string()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupport = z.object({
    id: z.number().int().readonly().optional(),
    project: z.string().readonly().optional(),
    origin: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    transactions: z.array(z.string()).readonly().optional(),
    money: zMoneyOutput.optional(),
    anonymous: z.boolean().default(true),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportTotalizedMoney = z.object({
    amount: z.number().int().optional(),
    currency: z.string().optional(),
    length: z.number().int().optional()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportTotalizedMoneyJsonld = z.object({
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    amount: z.number().int().optional(),
    currency: z.string().optional(),
    length: z.number().int().optional()
});

/**
 * ProjectSupports gather Transactions going from one same origin to one same Project.\
 * \
 * MatchCalls specially might make several different Transactions to the same Project,
 * but their ProjectSupport remains the same just with updated money.
 */
export const zProjectSupportJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    project: z.string().readonly().optional(),
    origin: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    transactions: z.array(z.string()).readonly().optional(),
    money: zMoneyOutputJsonld.optional(),
    anonymous: z.boolean().default(true),
    message: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * A ProjectUpdate offers records of significant news during a Project's life.\
 * \
 * Updates can be for outstanding donation amounts, achievement of goals or thresholds,
 * or any other body of information that the Project owner(s) may wish to make public to the Project's audience.
 */
export const zProjectUpdate = z.object({
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    subtitle: z.string(),
    body: z.string(),
    date: z.string().datetime().optional().default('now'),
    cover: z.string().url().optional(),
    author: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * A ProjectUpdate offers records of significant news during a Project's life.\
 * \
 * Updates can be for outstanding donation amounts, achievement of goals or thresholds,
 * or any other body of information that the Project owner(s) may wish to make public to the Project's audience.
 */
export const zProjectUpdateJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    project: z.string(),
    title: z.string(),
    subtitle: z.string(),
    body: z.string(),
    date: z.string().datetime().optional().default('now'),
    cover: z.string().url().optional(),
    author: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    locales: z.array(z.string()).readonly().optional(),
    dateCreated: z.string().datetime().readonly().optional(),
    dateUpdated: z.string().datetime().readonly().optional()
});

/**
 * Unlike other Money recipients a Tipjar receives money with no further goal.\
 * \
 * Tips to the platform owners and other no-purpose money can target a Tipjar.
 */
export const zTipjar = z.object({
    id: z.number().int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    name: z.string()
});

/**
 * Unlike other Money recipients a Tipjar receives money with no further goal.\
 * \
 * Tips to the platform owners and other no-purpose money can target a Tipjar.
 */
export const zTipjarJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    accounting: z.string().readonly().optional(),
    name: z.string()
});

/**
 * Users represent people who interact with the platform.
 */
export const zUser = z.object({
    id: z.number().int().readonly().optional(),
    email: z.string().email(),
    handle: z.string().min(4).max(30).regex(/^([a-z0-9_]+)$/),
    avatar: z.string().url().optional(),
    type: z.enum([
        'individual',
        'organization'
    ]).optional(),
    roles: z.array(z.string()).optional(),
    displayName: z.string().readonly().optional(),
    person: z.string().readonly().optional(),
    organization: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    accounting: z.string().readonly().optional(),
    projects: z.array(z.string()).readonly().optional(),
    emailConfirmed: z.boolean().readonly().optional(),
    active: z.boolean().readonly().optional(),
    links: z.array(zLink).readonly().optional()
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserUserSignupDto = z.object({
    email: z.string().email(),
    password: z.string().min(8),
    type: z.enum([
        'individual',
        'organization'
    ])
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserUserSignupDtoJsonld = z.object({
    email: z.string().email(),
    password: z.string().min(8),
    type: z.enum([
        'individual',
        'organization'
    ])
});

/**
 * Users represent people who interact with the platform.
 */
export const zUserJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.number().int().readonly().optional(),
    email: z.string().email(),
    handle: z.string().min(4).max(30).regex(/^([a-z0-9_]+)$/),
    avatar: z.string().url().optional(),
    type: z.enum([
        'individual',
        'organization'
    ]).optional(),
    roles: z.array(z.string()).optional(),
    displayName: z.string().readonly().optional(),
    person: z.string().readonly().optional(),
    organization: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    accounting: z.string().readonly().optional(),
    projects: z.array(z.string()).readonly().optional(),
    emailConfirmed: z.boolean().readonly().optional(),
    active: z.boolean().readonly().optional(),
    links: z.array(zLinkJsonld).readonly().optional()
});

/**
 * Some resources are versioned. This means v4 keeps track of the changes performed in subsets of specific properties within these resources.\
 * \
 * This allows us to keep track of the flow and the evolution of records in the platform.
 * Looking at the changes done between one version and the next one we can reconstruct how a resource was at a certain point in time.
 */
export const zVersion = z.object({
    id: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    action: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    resource: z.string().readonly().optional(),
    resourceId: z.number().int().readonly().optional(),
    resourceVersion: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    resourceChanges: z.unknown().readonly().optional(),
    dateCreated: z.union([
        z.string().datetime().readonly(),
        z.null()
    ]).readonly().optional()
});

/**
 * Some resources are versioned. This means v4 keeps track of the changes performed in subsets of specific properties within these resources.\
 * \
 * This allows us to keep track of the flow and the evolution of records in the platform.
 * Looking at the changes done between one version and the next one we can reconstruct how a resource was at a certain point in time.
 */
export const zVersionJsonld = z.object({
    '@context': z.union([
        z.string(),
        z.object({
            '@vocab': z.string(),
            hydra: z.enum([
                'http://www.w3.org/ns/hydra/core#'
            ])
        })
    ]).optional(),
    '@id': z.string().readonly().optional(),
    '@type': z.string().readonly().optional(),
    id: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    action: z.union([
        z.string().readonly(),
        z.null()
    ]).readonly().optional(),
    resource: z.string().readonly().optional(),
    resourceId: z.number().int().readonly().optional(),
    resourceVersion: z.union([
        z.number().int().readonly(),
        z.null()
    ]).readonly().optional(),
    resourceChanges: z.unknown().readonly().optional(),
    dateCreated: z.union([
        z.string().datetime().readonly(),
        z.null()
    ]).readonly().optional()
});

/**
 * The collection page number
 */
export const zApiAccountingsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiAccountingsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * Accounting collection
 */
export const zApiAccountingsGetCollectionResponse = z.array(zAccounting);

/**
 * Accounting identifier
 */
export const zApiAccountingsIdGetParameterId = z.string();

/**
 * Accounting resource
 */
export const zApiAccountingsIdGetResponse = zAccounting;

/**
 * The updated Accounting resource
 */
export const zApiAccountingsIdPatchData = zAccounting;

/**
 * Accounting identifier
 */
export const zApiAccountingsIdPatchParameterId = z.string();

/**
 * Accounting resource updated
 */
export const zApiAccountingsIdPatchResponse = zAccounting;

/**
 * The collection page number
 */
export const zApiAccountingBalancePointsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiAccountingBalancePointsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * AccountingBalancePoint accounting
 */
export const zApiAccountingBalancePointsGetCollectionParameterAccounting = z.string();

/**
 * AccountingBalancePoint start
 */
export const zApiAccountingBalancePointsGetCollectionParameterStart = z.string().datetime();

/**
 * AccountingBalancePoint interval
 */
export const zApiAccountingBalancePointsGetCollectionParameterInterval = z.string().default('24h');

/**
 * AccountingBalancePoint end
 */
export const zApiAccountingBalancePointsGetCollectionParameterEnd = z.string().datetime().default('now');

/**
 * If true, the balance points are cumulative over time.
 */
export const zApiAccountingBalancePointsGetCollectionParameterAggregate = z.boolean().default(false);

/**
 * AccountingBalancePoint collection
 */
export const zApiAccountingBalancePointsGetCollectionResponse = z.array(zAccountingBalancePoint);

/**
 * The collection page number
 */
export const zApiAccountingTransactionsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiAccountingTransactionsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiAccountingTransactionsGetCollectionParameterOrigin = z.string();

export const zApiAccountingTransactionsGetCollectionParameterTarget = z.string();

/**
 * AccountingTransaction collection
 */
export const zApiAccountingTransactionsGetCollectionResponse = z.array(zAccountingTransaction);

/**
 * AccountingTransaction identifier
 */
export const zApiAccountingTransactionsIdGetParameterId = z.string();

/**
 * AccountingTransaction resource
 */
export const zApiAccountingTransactionsIdGetResponse = zAccountingTransaction;

/**
 * The collection page number
 */
export const zApiCategoriesGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiCategoriesGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * Category collection
 */
export const zApiCategoriesGetCollectionResponse = z.array(zCategory);

/**
 * Category identifier
 */
export const zApiCategoriesIdGetParameterId = z.string();

/**
 * Category resource
 */
export const zApiCategoriesIdGetResponse = zCategory;

/**
 * The collection page number
 */
export const zApiGatewaysGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiGatewaysGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * Gateway collection
 */
export const zApiGatewaysGetCollectionResponse = z.array(zGateway);

/**
 * Gateway identifier
 */
export const zApiGatewaysNameGetParameterName = z.string();

/**
 * Gateway resource
 */
export const zApiGatewaysNameGetResponse = zGateway;

/**
 * The collection page number
 */
export const zApiGatewayChargesGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiGatewayChargesGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiGatewayChargesGetCollectionParameterCheckoutGateway = z.string();

export const zApiGatewayChargesGetCollectionParameterCheckoutTrackingsValue = z.string();

export const zApiGatewayChargesGetCollectionParameterType = z.string();

export const zApiGatewayChargesGetCollectionParameterTarget = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyCurrency = z.string();

export const zApiGatewayChargesGetCollectionParameterStatus = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyAmountBetween = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyAmountGt = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyAmountGte = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyAmountLt = z.string();

export const zApiGatewayChargesGetCollectionParameterMoneyAmountLte = z.string();

export const zApiGatewayChargesGetCollectionParameterDateCreatedBefore = z.string();

export const zApiGatewayChargesGetCollectionParameterDateCreatedStrictlyBefore = z.string();

export const zApiGatewayChargesGetCollectionParameterDateCreatedAfter = z.string();

export const zApiGatewayChargesGetCollectionParameterDateCreatedStrictlyAfter = z.string();

export const zApiGatewayChargesGetCollectionParameterDateUpdatedBefore = z.string();

export const zApiGatewayChargesGetCollectionParameterDateUpdatedStrictlyBefore = z.string();

export const zApiGatewayChargesGetCollectionParameterDateUpdatedAfter = z.string();

export const zApiGatewayChargesGetCollectionParameterDateUpdatedStrictlyAfter = z.string();

export const zApiGatewayChargesGetCollectionParameterOrderDateCreated = z.enum([
    'asc',
    'desc'
]);

export const zApiGatewayChargesGetCollectionParameterOrderDateUpdated = z.enum([
    'asc',
    'desc'
]);

/**
 * GatewayCharge collection
 */
export const zApiGatewayChargesGetCollectionResponse = z.array(zGatewayCharge);

/**
 * GatewayCharge identifier
 */
export const zApiGatewayChargesIdGetParameterId = z.string();

/**
 * GatewayCharge resource
 */
export const zApiGatewayChargesIdGetResponse = zGatewayCharge;

/**
 * The updated GatewayCharge resource
 */
export const zApiGatewayChargesIdPatchData = zGatewayChargeChargeUpdationDto;

/**
 * GatewayCharge identifier
 */
export const zApiGatewayChargesIdPatchParameterId = z.string();

/**
 * GatewayCharge resource updated
 */
export const zApiGatewayChargesIdPatchResponse = zGatewayCharge;

/**
 * The collection page number
 */
export const zApiGatewayCheckoutsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiGatewayCheckoutsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * GatewayCheckout collection
 */
export const zApiGatewayCheckoutsGetCollectionResponse = z.array(zGatewayCheckout);

/**
 * The new GatewayCheckout resource
 */
export const zApiGatewayCheckoutsPostData = zGatewayCheckoutCheckoutCreationDto;

/**
 * GatewayCheckout resource created
 */
export const zApiGatewayCheckoutsPostResponse = zGatewayCheckout;

/**
 * GatewayCheckout identifier
 */
export const zApiGatewayCheckoutsIdGetParameterId = z.string();

/**
 * GatewayCheckout resource
 */
export const zApiGatewayCheckoutsIdGetResponse = zGatewayCheckout;

/**
 * The updated GatewayCheckout resource
 */
export const zApiGatewayCheckoutsIdPatchData = zGatewayCheckoutCheckoutUpdationDto;

/**
 * GatewayCheckout identifier
 */
export const zApiGatewayCheckoutsIdPatchParameterId = z.string();

/**
 * GatewayCheckout resource updated
 */
export const zApiGatewayCheckoutsIdPatchResponse = zGatewayCheckout;

/**
 * The collection page number
 */
export const zApiMatchCallsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiMatchCallsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiMatchCallsGetCollectionParameterAccounting = z.string();

export const zApiMatchCallsGetCollectionParameterTitle = z.string();

export const zApiMatchCallsGetCollectionParameterDescription = z.string();

export const zApiMatchCallsGetCollectionParameterTerritoryCountry = z.string();

export const zApiMatchCallsGetCollectionParameterTerritorySubLvl1 = z.string();

export const zApiMatchCallsGetCollectionParameterTerritorySubLvl2 = z.string();

export const zApiMatchCallsGetCollectionParameterStatus = z.string();

/**
 * MatchCall collection
 */
export const zApiMatchCallsGetCollectionResponse = z.array(zMatchCall);

/**
 * The new MatchCall resource
 */
export const zApiMatchCallsPostData = zMatchCall;

/**
 * MatchCall resource created
 */
export const zApiMatchCallsPostResponse = zMatchCall;

/**
 * MatchCall identifier
 */
export const zApiMatchCallsIdDeleteParameterId = z.string();

/**
 * MatchCall resource deleted
 */
export const zApiMatchCallsIdDeleteResponse = z.void();

/**
 * MatchCall identifier
 */
export const zApiMatchCallsIdGetParameterId = z.string();

/**
 * MatchCall resource
 */
export const zApiMatchCallsIdGetResponse = zMatchCall;

/**
 * The updated MatchCall resource
 */
export const zApiMatchCallsIdPatchData = zMatchCall;

/**
 * MatchCall identifier
 */
export const zApiMatchCallsIdPatchParameterId = z.string();

/**
 * MatchCall resource updated
 */
export const zApiMatchCallsIdPatchResponse = zMatchCall;

/**
 * The collection page number
 */
export const zApiMatchCallSubmissionsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiMatchCallSubmissionsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiMatchCallSubmissionsGetCollectionParameterCall = z.string();

export const zApiMatchCallSubmissionsGetCollectionParameterProject = z.string();

export const zApiMatchCallSubmissionsGetCollectionParameterStatus = z.string();

/**
 * MatchCallSubmission collection
 */
export const zApiMatchCallSubmissionsGetCollectionResponse = z.array(zMatchCallSubmission);

/**
 * The new MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsPostData = zMatchCallSubmissionMatchCallSubmissionCreationDto;

/**
 * MatchCallSubmission resource created
 */
export const zApiMatchCallSubmissionsPostResponse = zMatchCallSubmission;

/**
 * MatchCallSubmission identifier
 */
export const zApiMatchCallSubmissionsIdGetParameterId = z.string();

/**
 * MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsIdGetResponse = zMatchCallSubmission;

/**
 * The updated MatchCallSubmission resource
 */
export const zApiMatchCallSubmissionsIdPatchData = zMatchCallSubmission;

/**
 * MatchCallSubmission identifier
 */
export const zApiMatchCallSubmissionsIdPatchParameterId = z.string();

/**
 * MatchCallSubmission resource updated
 */
export const zApiMatchCallSubmissionsIdPatchResponse = zMatchCallSubmission;

/**
 * The collection page number
 */
export const zApiMatchFormulasGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiMatchFormulasGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * MatchFormula collection
 */
export const zApiMatchFormulasGetCollectionResponse = z.array(zMatchFormula);

/**
 * MatchFormula identifier
 */
export const zApiMatchFormulasNameGetParameterName = z.string();

/**
 * MatchFormula resource
 */
export const zApiMatchFormulasNameGetResponse = zMatchFormula;

/**
 * The collection page number
 */
export const zApiMatchRulesGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiMatchRulesGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * MatchRule collection
 */
export const zApiMatchRulesGetCollectionResponse = z.array(zMatchRule);

/**
 * MatchRule identifier
 */
export const zApiMatchRulesNameGetParameterName = z.string();

/**
 * MatchRule resource
 */
export const zApiMatchRulesNameGetResponse = zMatchRule;

/**
 * The collection page number
 */
export const zApiMatchStrategiesGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiMatchStrategiesGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiMatchStrategiesGetCollectionParameterCall = z.string();

export const zApiMatchStrategiesGetCollectionParameterOrderRanking = z.enum([
    'asc',
    'desc'
]);

/**
 * MatchStrategy collection
 */
export const zApiMatchStrategiesGetCollectionResponse = z.array(zMatchStrategy);

/**
 * The new MatchStrategy resource
 */
export const zApiMatchStrategiesPostData = zMatchStrategy;

/**
 * MatchStrategy resource created
 */
export const zApiMatchStrategiesPostResponse = zMatchStrategy;

/**
 * MatchStrategy identifier
 */
export const zApiMatchStrategiesIdDeleteParameterId = z.string();

/**
 * MatchStrategy resource deleted
 */
export const zApiMatchStrategiesIdDeleteResponse = z.void();

/**
 * MatchStrategy identifier
 */
export const zApiMatchStrategiesIdGetParameterId = z.string();

/**
 * MatchStrategy resource
 */
export const zApiMatchStrategiesIdGetResponse = zMatchStrategy;

/**
 * The updated MatchStrategy resource
 */
export const zApiMatchStrategiesIdPatchData = zMatchStrategy;

/**
 * MatchStrategy identifier
 */
export const zApiMatchStrategiesIdPatchParameterId = z.string();

/**
 * MatchStrategy resource updated
 */
export const zApiMatchStrategiesIdPatchResponse = zMatchStrategy;

/**
 * User identifier
 */
export const zApiUsersIdorganizationGetParameterId = z.string();

/**
 * Organization resource
 */
export const zApiUsersIdorganizationGetResponse = zOrganization;

/**
 * The updated Organization resource
 */
export const zApiUsersIdorganizationPatchData = zOrganization;

/**
 * User identifier
 */
export const zApiUsersIdorganizationPatchParameterId = z.string();

/**
 * Organization resource updated
 */
export const zApiUsersIdorganizationPatchResponse = zOrganization;

/**
 * User identifier
 */
export const zApiUsersIdpersonGetParameterId = z.string();

/**
 * Person resource
 */
export const zApiUsersIdpersonGetResponse = zPerson;

/**
 * The updated Person resource
 */
export const zApiUsersIdpersonPatchData = zPerson;

/**
 * User identifier
 */
export const zApiUsersIdpersonPatchParameterId = z.string();

/**
 * Person resource updated
 */
export const zApiUsersIdpersonPatchResponse = zPerson;

/**
 * Ping resource
 */
export const zApiPingGetResponse = zPing;

/**
 * The collection page number
 */
export const zApiProjectsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectsGetCollectionParameterSlug = z.string();

export const zApiProjectsGetCollectionParameterAccounting = z.string();

export const zApiProjectsGetCollectionParameterOwner = z.string();

export const zApiProjectsGetCollectionParameterTitle = z.string();

export const zApiProjectsGetCollectionParameterSubtitle = z.string();

export const zApiProjectsGetCollectionParameterCategories = z.string();

export const zApiProjectsGetCollectionParameterTerritoryCountry = z.string();

export const zApiProjectsGetCollectionParameterTerritorySubLvl1 = z.string();

export const zApiProjectsGetCollectionParameterTerritorySubLvl2 = z.string();

export const zApiProjectsGetCollectionParameterDescription = z.string();

export const zApiProjectsGetCollectionParameterStatus = z.string();

export const zApiProjectsGetCollectionParameterDateCreatedBefore = z.string();

export const zApiProjectsGetCollectionParameterDateCreatedStrictlyBefore = z.string();

export const zApiProjectsGetCollectionParameterDateCreatedAfter = z.string();

export const zApiProjectsGetCollectionParameterDateCreatedStrictlyAfter = z.string();

export const zApiProjectsGetCollectionParameterOrderDateCreated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectsGetCollectionParameterOrderDateUpdated = z.enum([
    'asc',
    'desc'
]);

/**
 * Project collection
 */
export const zApiProjectsGetCollectionResponse = z.array(zProject);

/**
 * The new Project resource
 */
export const zApiProjectsPostData = zProjectProjectCreationDto;

/**
 * Project resource created
 */
export const zApiProjectsPostResponse = zProject;

/**
 * Project identifier or slug
 */
export const zApiProjectsIdOrSlugGetParameterIdOrSlug = z.string();

/**
 * Project resource
 */
export const zApiProjectsIdOrSlugGetResponse = zProject;

/**
 * Project identifier
 */
export const zApiProjectsIdDeleteParameterId = z.string();

/**
 * Project resource deleted
 */
export const zApiProjectsIdDeleteResponse = z.void();

/**
 * The updated Project resource
 */
export const zApiProjectsIdPatchData = zProjectProjectUpdationDto;

/**
 * Project identifier
 */
export const zApiProjectsIdPatchParameterId = z.string();

/**
 * Project resource updated
 */
export const zApiProjectsIdPatchResponse = zProject;

/**
 * The collection page number
 */
export const zApiProjectBudgetItemsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectBudgetItemsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectBudgetItemsGetCollectionParameterProject = z.string();

/**
 * ProjectBudgetItem collection
 */
export const zApiProjectBudgetItemsGetCollectionResponse = z.array(zProjectBudgetItem);

/**
 * The new ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsPostData = zProjectBudgetItem;

/**
 * ProjectBudgetItem resource created
 */
export const zApiProjectBudgetItemsPostResponse = zProjectBudgetItem;

/**
 * ProjectBudgetItem identifier
 */
export const zApiProjectBudgetItemsIdDeleteParameterId = z.string();

/**
 * ProjectBudgetItem resource deleted
 */
export const zApiProjectBudgetItemsIdDeleteResponse = z.void();

/**
 * ProjectBudgetItem identifier
 */
export const zApiProjectBudgetItemsIdGetParameterId = z.string();

/**
 * ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsIdGetResponse = zProjectBudgetItem;

/**
 * The updated ProjectBudgetItem resource
 */
export const zApiProjectBudgetItemsIdPatchData = zProjectBudgetItem;

/**
 * ProjectBudgetItem identifier
 */
export const zApiProjectBudgetItemsIdPatchParameterId = z.string();

/**
 * ProjectBudgetItem resource updated
 */
export const zApiProjectBudgetItemsIdPatchResponse = zProjectBudgetItem;

/**
 * The collection page number
 */
export const zApiProjectCollaborationsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectCollaborationsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectCollaborationsGetCollectionParameterProject = z.string();

export const zApiProjectCollaborationsGetCollectionParameterIsFulfilled = z.boolean();

export const zApiProjectCollaborationsGetCollectionParameterDateCreatedBefore = z.string();

export const zApiProjectCollaborationsGetCollectionParameterDateCreatedStrictlyBefore = z.string();

export const zApiProjectCollaborationsGetCollectionParameterDateCreatedAfter = z.string();

export const zApiProjectCollaborationsGetCollectionParameterDateCreatedStrictlyAfter = z.string();

export const zApiProjectCollaborationsGetCollectionParameterOrderDateCreated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectCollaborationsGetCollectionParameterOrderDateUpdated = z.enum([
    'asc',
    'desc'
]);

/**
 * ProjectCollaboration collection
 */
export const zApiProjectCollaborationsGetCollectionResponse = z.array(zProjectCollaboration);

/**
 * The new ProjectCollaboration resource
 */
export const zApiProjectCollaborationsPostData = zProjectCollaboration;

/**
 * ProjectCollaboration resource created
 */
export const zApiProjectCollaborationsPostResponse = zProjectCollaboration;

/**
 * ProjectCollaboration identifier
 */
export const zApiProjectCollaborationsIdDeleteParameterId = z.string();

/**
 * ProjectCollaboration resource deleted
 */
export const zApiProjectCollaborationsIdDeleteResponse = z.void();

/**
 * ProjectCollaboration identifier
 */
export const zApiProjectCollaborationsIdGetParameterId = z.string();

/**
 * ProjectCollaboration resource
 */
export const zApiProjectCollaborationsIdGetResponse = zProjectCollaboration;

/**
 * The updated ProjectCollaboration resource
 */
export const zApiProjectCollaborationsIdPatchData = zProjectCollaboration;

/**
 * ProjectCollaboration identifier
 */
export const zApiProjectCollaborationsIdPatchParameterId = z.string();

/**
 * ProjectCollaboration resource updated
 */
export const zApiProjectCollaborationsIdPatchResponse = zProjectCollaboration;

/**
 * The collection page number
 */
export const zApiProjectRewardsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectRewardsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectRewardsGetCollectionParameterProject = z.string();

export const zApiProjectRewardsGetCollectionParameterOrderMoneyAmount = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectRewardsGetCollectionParameterOrderUnitsClaimed = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectRewardsGetCollectionParameterOrderUnitsAvailable = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectRewardsGetCollectionParameterOrderDateCreated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectRewardsGetCollectionParameterOrderDateUpdated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectRewardsGetCollectionParameterIsFinite = z.boolean();

export const zApiProjectRewardsGetCollectionParameterDateCreatedBefore = z.string();

export const zApiProjectRewardsGetCollectionParameterDateCreatedStrictlyBefore = z.string();

export const zApiProjectRewardsGetCollectionParameterDateCreatedAfter = z.string();

export const zApiProjectRewardsGetCollectionParameterDateCreatedStrictlyAfter = z.string();

/**
 * ProjectReward collection
 */
export const zApiProjectRewardsGetCollectionResponse = z.array(zProjectReward);

/**
 * The new ProjectReward resource
 */
export const zApiProjectRewardsPostData = zProjectReward;

/**
 * ProjectReward resource created
 */
export const zApiProjectRewardsPostResponse = zProjectReward;

/**
 * ProjectReward identifier
 */
export const zApiProjectRewardsIdDeleteParameterId = z.string();

/**
 * ProjectReward resource deleted
 */
export const zApiProjectRewardsIdDeleteResponse = z.void();

/**
 * ProjectReward identifier
 */
export const zApiProjectRewardsIdGetParameterId = z.string();

/**
 * ProjectReward resource
 */
export const zApiProjectRewardsIdGetResponse = zProjectReward;

/**
 * The updated ProjectReward resource
 */
export const zApiProjectRewardsIdPatchData = zProjectReward;

/**
 * ProjectReward identifier
 */
export const zApiProjectRewardsIdPatchParameterId = z.string();

/**
 * ProjectReward resource updated
 */
export const zApiProjectRewardsIdPatchResponse = zProjectReward;

/**
 * The collection page number
 */
export const zApiProjectRewardClaimsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectRewardClaimsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectRewardClaimsGetCollectionParameterOwner = z.string();

export const zApiProjectRewardClaimsGetCollectionParameterCharge = z.string();

export const zApiProjectRewardClaimsGetCollectionParameterReward = z.string();

/**
 * ProjectRewardClaim collection
 */
export const zApiProjectRewardClaimsGetCollectionResponse = z.array(zProjectRewardClaim);

/**
 * The new ProjectRewardClaim resource
 */
export const zApiProjectRewardClaimsPostData = zProjectRewardClaimRewardClaimCreationDto;

/**
 * ProjectRewardClaim resource created
 */
export const zApiProjectRewardClaimsPostResponse = zProjectRewardClaim;

/**
 * ProjectRewardClaim identifier
 */
export const zApiProjectRewardClaimsIdDeleteParameterId = z.string();

/**
 * ProjectRewardClaim resource deleted
 */
export const zApiProjectRewardClaimsIdDeleteResponse = z.void();

/**
 * ProjectRewardClaim identifier
 */
export const zApiProjectRewardClaimsIdGetParameterId = z.string();

/**
 * ProjectRewardClaim resource
 */
export const zApiProjectRewardClaimsIdGetResponse = zProjectRewardClaim;

/**
 * The collection page number
 */
export const zApiProjectSupportsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectSupportsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectSupportsGetCollectionParameterProject = z.string();

export const zApiProjectSupportsGetCollectionParameterOrigin = z.string();

export const zApiProjectSupportsGetCollectionParameterAnonymous = z.boolean();

/**
 * ProjectSupport collection
 */
export const zApiProjectSupportsGetCollectionResponse = z.array(zProjectSupport);

export const zApiProjectSupportsmoneyTotalGetCollectionParameterProject = z.string();

export const zApiProjectSupportsmoneyTotalGetCollectionParameterOrigin = z.string();

export const zApiProjectSupportsmoneyTotalGetCollectionParameterAnonymous = z.boolean();

/**
 * Totalized money
 */
export const zApiProjectSupportsmoneyTotalGetCollectionResponse = zProjectSupportTotalizedMoney;

/**
 * ProjectSupport identifier
 */
export const zApiProjectSupportsIdGetParameterId = z.string();

/**
 * ProjectSupport resource
 */
export const zApiProjectSupportsIdGetResponse = zProjectSupport;

/**
 * The updated ProjectSupport resource
 */
export const zApiProjectSupportsIdPatchData = zProjectSupport;

/**
 * ProjectSupport identifier
 */
export const zApiProjectSupportsIdPatchParameterId = z.string();

/**
 * ProjectSupport resource updated
 */
export const zApiProjectSupportsIdPatchResponse = zProjectSupport;

/**
 * The collection page number
 */
export const zApiProjectUpdatesGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiProjectUpdatesGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiProjectUpdatesGetCollectionParameterProject = z.string();

export const zApiProjectUpdatesGetCollectionParameterAuthor = z.string();

export const zApiProjectUpdatesGetCollectionParameterOrderDate = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectUpdatesGetCollectionParameterOrderDateCreated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectUpdatesGetCollectionParameterOrderDateUpdated = z.enum([
    'asc',
    'desc'
]);

export const zApiProjectUpdatesGetCollectionParameterDateCreatedBefore = z.string();

export const zApiProjectUpdatesGetCollectionParameterDateCreatedStrictlyBefore = z.string();

export const zApiProjectUpdatesGetCollectionParameterDateCreatedAfter = z.string();

export const zApiProjectUpdatesGetCollectionParameterDateCreatedStrictlyAfter = z.string();

/**
 * ProjectUpdate collection
 */
export const zApiProjectUpdatesGetCollectionResponse = z.array(zProjectUpdate);

/**
 * The new ProjectUpdate resource
 */
export const zApiProjectUpdatesPostData = zProjectUpdate;

/**
 * ProjectUpdate resource created
 */
export const zApiProjectUpdatesPostResponse = zProjectUpdate;

/**
 * ProjectUpdate identifier
 */
export const zApiProjectUpdatesIdDeleteParameterId = z.string();

/**
 * ProjectUpdate resource deleted
 */
export const zApiProjectUpdatesIdDeleteResponse = z.void();

/**
 * ProjectUpdate identifier
 */
export const zApiProjectUpdatesIdGetParameterId = z.string();

/**
 * ProjectUpdate resource
 */
export const zApiProjectUpdatesIdGetResponse = zProjectUpdate;

/**
 * The updated ProjectUpdate resource
 */
export const zApiProjectUpdatesIdPatchData = zProjectUpdate;

/**
 * ProjectUpdate identifier
 */
export const zApiProjectUpdatesIdPatchParameterId = z.string();

/**
 * ProjectUpdate resource updated
 */
export const zApiProjectUpdatesIdPatchResponse = zProjectUpdate;

/**
 * The collection page number
 */
export const zApiTipjarsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiTipjarsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiTipjarsGetCollectionParameterAccounting = z.string();

export const zApiTipjarsGetCollectionParameterName = z.string();

/**
 * Tipjar collection
 */
export const zApiTipjarsGetCollectionResponse = z.array(zTipjar);

/**
 * The new Tipjar resource
 */
export const zApiTipjarsPostData = zTipjar;

/**
 * Tipjar resource created
 */
export const zApiTipjarsPostResponse = zTipjar;

/**
 * Tipjar identifier
 */
export const zApiTipjarsIdDeleteParameterId = z.string();

/**
 * Tipjar resource deleted
 */
export const zApiTipjarsIdDeleteResponse = z.void();

/**
 * Tipjar identifier
 */
export const zApiTipjarsIdGetParameterId = z.string();

/**
 * Tipjar resource
 */
export const zApiTipjarsIdGetResponse = zTipjar;

/**
 * The updated Tipjar resource
 */
export const zApiTipjarsIdPatchData = zTipjar;

/**
 * Tipjar identifier
 */
export const zApiTipjarsIdPatchParameterId = z.string();

/**
 * Tipjar resource updated
 */
export const zApiTipjarsIdPatchResponse = zTipjar;

/**
 * The collection page number
 */
export const zApiUsersGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiUsersGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

export const zApiUsersGetCollectionParameterEmail = z.string();

export const zApiUsersGetCollectionParameterAccounting = z.string();

export const zApiUsersGetCollectionParameterHandle = z.string();

/**
 * User collection
 */
export const zApiUsersGetCollectionResponse = z.array(zUser);

/**
 * The new User resource
 */
export const zApiUsersPostData = zUserUserSignupDto;

/**
 * Only available to admin users
 */
export const zApiUsersPostParameterEmail = z.string();

/**
 * User resource created
 */
export const zApiUsersPostResponse = zUser;

/**
 * User identifier or handle
 */
export const zApiUsersIdOrHandleGetParameterIdOrHandle = z.string();

/**
 * Only available to admin users
 */
export const zApiUsersIdOrHandleGetParameterEmail = z.string();

/**
 * User resource
 */
export const zApiUsersIdOrHandleGetResponse = zUser;

/**
 * User identifier
 */
export const zApiUsersIdDeleteParameterId = z.string();

/**
 * Only available to admin users
 */
export const zApiUsersIdDeleteParameterEmail = z.string();

/**
 * User resource deleted
 */
export const zApiUsersIdDeleteResponse = z.void();

/**
 * The updated User resource
 */
export const zApiUsersIdPatchData = zUser;

/**
 * User identifier
 */
export const zApiUsersIdPatchParameterId = z.string();

/**
 * Only available to admin users
 */
export const zApiUsersIdPatchParameterEmail = z.string();

/**
 * User resource updated
 */
export const zApiUsersIdPatchResponse = zUser;

/**
 * The collection page number
 */
export const zApiVersionsGetCollectionParameterPage = z.number().int().default(1);

/**
 * The number of items per page
 */
export const zApiVersionsGetCollectionParameterItemsPerPage = z.number().int().gte(0).lte(100).default(30);

/**
 * The name of the resource.
 */
export const zApiVersionsGetCollectionParameterResource = z.enum([
    'GatewayCharge',
    'GatewayCheckout',
    'User'
]);

/**
 * The ID of the named resource.
 */
export const zApiVersionsGetCollectionParameterResourceId = z.number().int();

/**
 * Version collection
 */
export const zApiVersionsGetCollectionResponse = z.array(zVersion);

/**
 * Version identifier
 */
export const zApiVersionsIdGetParameterId = z.string();

/**
 * Version resource
 */
export const zApiVersionsIdGetResponse = zVersion;