name = "goteo-v4-frontend"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
keep_vars = true

[assets]
binding = "ASSETS"
directory = "./dist"

[observability.logs]
enabled = true

[env.testing]
routes = [
    { pattern = "testing.v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[env.staging]
routes = [
    { pattern = "staging.v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[env.beta]
routes = [
    { pattern = "new.goteo.org", zone_name = "goteo.org", custom_domain = true },
]

[env.prod]
routes = [
    { pattern = "v4.goteo.org", zone_name = "goteo.org", custom_domain = true },
]
[env.preview]
workers_dev = true
