name: Deploy PR Preview

on:
    pull_request:
        branches:
            - staging
            - main
permissions:
    pull-requests: write
    contents: read

jobs:
    preview:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm run build

            - name: Get Cloudflare secrets
              run: |
                  echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
                  echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV

            - name: Send secrets to Cloudflare
              run: |
                  for secret in API_URL API_VERSION PLATONIQ_ACCOUNTING_ID FACEBOOK_APP_ID PUBLIC_CURRENCY_DEFAULT PUBLIC_LANGUAGE_DEFAULT; do
                  echo "${!secret}" | pnpm exec wrangler secret put $secret --env preview --name goteo-pr-${{ github.event.pull_request.number }}-preview --yes
                  done
              env:
                  API_URL: ${{ secrets.API_URL }}
                  API_VERSION: ${{ secrets.API_VERSION }}
                  PLATONIQ_ACCOUNTING_ID: ${{ secrets.PLATONIQ_ACCOUNTING_ID }}
                  FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
                  PUBLIC_CURRENCY_DEFAULT: ${{ secrets.PUBLIC_CURRENCY_DEFAULT }}
                  PUBLIC_LANGUAGE_DEFAULT: ${{ secrets.PUBLIC_LANGUAGE_DEFAULT }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

            - name: Deploy Worker for PR
              run: pnpm exec wrangler deploy --env preview --name goteo-pr-${{ github.event.pull_request.number }}-preview
              env:
                  API_URL: ${{ secrets.API_URL }}
                  API_VERSION: ${{ secrets.API_VERSION }}
                  PLATONIQ_ACCOUNTING_ID: ${{ secrets.PLATONIQ_ACCOUNTING_ID }}
                  FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
                  PUBLIC_CURRENCY_DEFAULT: ${{ secrets.PUBLIC_CURRENCY_DEFAULT }}
                  PUBLIC_LANGUAGE_DEFAULT: ${{ secrets.PUBLIC_LANGUAGE_DEFAULT }}

            - name: Create route for custom subdomain
              run: >
                  curl -X POST "https://api.cloudflare.com/client/v4/zones/${{
                  secrets.CLOUDFLARE_ZONE_ID }}/workers/routes" \
                    -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    --data '{
                      "pattern": "pr-${{ github.event.pull_request.number }}.v4.preview.goteo.org",
                      "script": "goteo-pr-${{ github.event.pull_request.number }}-preview"
                    }'

            - name: Comment preview URL using GitHub Script
              uses: actions/github-script@v7
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
                  script: >
                      const prNumber = context.payload.pull_request.number;

                      const body = `**Preview URL:**  

                      [https://pr-${prNumber}.v4.preview.goteo.org](https://pr-${prNumber}.v4.preview.goteo.org)`;

                      const comments = await github.rest.issues.listComments({
                        ...context.repo,
                        issue_number: prNumber,
                      });

                      const existingComment = comments.data.find(c =>
                        c.body.includes('**Preview URL:**')
                      );

                      if (existingComment) {
                        await github.rest.issues.updateComment({
                          ...context.repo,
                          comment_id: existingComment.id,
                          body,
                        });
                      } else {
                        await github.rest.issues.createComment({
                          ...context.repo,
                          issue_number: prNumber,
                          body,
                        });
                      }
